const applicants = [
    // 책임의식
    {
      id: 1,
      name: "이유진",
      score: 80,
      birthdate: "2000. 01. 01",
      phone: "010-1234-5678",
      email: "kdt@kdt.com",
      location: "경기도 용인시",
      preferredJob: "서비스",
      certificates: "SQLD, 정보처리기사",
      experience: "삼성전자 2년, NC 소프트 3년",
      talent: "책임의식",
    },
    {
      id: 2,
      name: "홍길동",
      score: 70,
      birthdate: "2001. 03. 03",
      phone: "010-7777-6666",
      email: "hong@example.com",
      location: "인천광역시",
      preferredJob: "마케팅",
      certificates: "구글 애널리틱스",
      experience: "CJ 2년",
      talent: "책임의식",
    },
    {
      id: 3,
      name: "김수현",
      score: 85,
      birthdate: "1994. 06. 18",
      phone: "010-3456-7890",
      email: "su@example.com",
      location: "서울특별시",
      preferredJob: "재무",
      certificates: "CPA, CFA",
      experience: "삼성증권 5년",
      talent: "책임의식",
    },
    {
      id: 4,
      name: "박소민",
      score: 82,
      birthdate: "1998. 12. 22",
      phone: "010-6543-2109",
      email: "somin@example.com",
      location: "부산광역시",
      preferredJob: "HR",
      certificates: "HR 전문가 과정",
      experience: "SK 3년",
      talent: "책임의식",
    },
    {
      id: 5,
      name: "이정우",
      score: 77,
      birthdate: "1996. 09. 30",
      phone: "010-8765-4321",
      email: "jungwoo@example.com",
      location: "대전광역시",
      preferredJob: "품질 관리",
      certificates: "ISO 9001 전문가",
      experience: "LG화학 4년",
      talent: "책임의식",
    },
    {
      id: 6,
      name: "최나영",
      score: 79,
      birthdate: "1997. 07. 07",
      phone: "010-2233-4455",
      email: "nayoung@example.com",
      location: "광주광역시",
      preferredJob: "컨설팅",
      certificates: "컨설팅 전문가 과정",
      experience: "PwC 3년",
      talent: "책임의식",
    },
    {
      id: 7,
      name: "정한길",
      score: 81,
      birthdate: "1999. 02. 10",
      phone: "010-1122-3344",
      email: "hangil@example.com",
      location: "울산광역시",
      preferredJob: "운영관리",
      certificates: "SCM 전문가",
      experience: "현대자동차 3년",
      talent: "책임의식",
    },
  
    // 도전정신
    {
      id: 8,
      name: "김민수",
      score: 75,
      birthdate: "1998. 05. 20",
      phone: "010-5678-1234",
      email: "minsu@example.com",
      location: "서울특별시",
      preferredJob: "개발",
      certificates: "정보처리기사",
      experience: "카카오 3년",
      talent: "도전정신",
    },
    {
      id: 9,
      name: "정다은",
      score: 78,
      birthdate: "1996. 12. 25",
      phone: "010-4444-5555",
      email: "daeun@example.com",
      location: "강원도 춘천시",
      preferredJob: "영업",
      certificates: "세일즈 마케팅",
      experience: "롯데 3년",
      talent: "도전정신",
    },
    {
      id: 10,
      name: "손민호",
      score: 80,
      birthdate: "1995. 02. 17",
      phone: "010-1212-3434",
      email: "minho@example.com",
      location: "부산광역시",
      preferredJob: "기획",
      certificates: "PMP",
      experience: "네이버 5년",
      talent: "도전정신",
    },
    {
      id: 11,
      name: "유가영",
      score: 84,
      birthdate: "1999. 08. 21",
      phone: "010-8989-1212",
      email: "gayoung@example.com",
      location: "대구광역시",
      preferredJob: "디자인",
      certificates: "UX/UI 전문가 과정",
      experience: "LG전자 4년",
      talent: "도전정신",
    },
  
    // 소통협력
    {
      id: 12,
      name: "박지훈",
      score: 85,
      birthdate: "1995. 11. 15",
      phone: "010-9999-8888",
      email: "jihun@example.com",
      location: "부산광역시",
      preferredJob: "기획",
      certificates: "PMP",
      experience: "네이버 5년",
      talent: "소통협력",
    },
  
    // 창의성
    {
      id: 13,
      name: "최은지",
      score: 90,
      birthdate: "1997. 07. 07",
      phone: "010-2222-3333",
      email: "eunji@example.com",
      location: "대전광역시",
      preferredJob: "디자인",
      certificates: "UX/UI 전문가 과정",
      experience: "LG전자 4년",
      talent: "창의성",
    },
    {
      id: 14,
      name: "이서준",
      score: 88,
      birthdate: "1999. 09. 09",
      phone: "010-3333-2222",
      email: "seo@example.com",
      location: "대구광역시",
      preferredJob: "운영관리",
      certificates: "ERP 전문가",
      experience: "한화 2년",
      talent: "창의성",
    },
    {
      id: 15,
      name: "박윤하",
      score: 86,
      birthdate: "2000. 04. 03",
      phone: "010-9898-7878",
      email: "yunha@example.com",
      location: "서울특별시",
      preferredJob: "브랜드 전략",
      certificates: "마케팅 전문가 과정",
      experience: "CJ ENM 3년",
      talent: "창의성",
    },
  ];
  
  export default applicants;
  